# Generated by Django 5.1.7 on 2025-04-04 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='job',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
    ]
