# Generated by Django 4.2.20 on 2025-04-02 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Formula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Formula Name')),
                ('image', models.ImageField(upload_to='formula/')),
                ('variables', models.JSONField(blank=True, null=True, verbose_name='Used Variables')),
                ('latex_data', models.TextField(default='x=(-b±√(b^2-4ac))/(2a)', verbose_name='Latex Data')),
                ('code', models.TextField(default='# Agar qaysidir kutubxonadan foydalansangiz, ularni import qiling\ndef solution(a, b, c):\n    # Siz o\'zingizni formulangizni yozasiz\n    \n    discriminant = b**2 - 4*a*c\n    \n    if discriminant < 0:\n        return "No real roots"\n    \n    x1 = (-b + (discriminant ** (1/2))) / (2*a)\n    x2 = (-b - (discriminant ** (1/2))) / (2*a)\n    \n    return x1, x2\n', verbose_name='Python Code')),
                ('formula_img', models.ImageField(blank=True, null=True, upload_to='formula/')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FunksionalData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=150)),
                ('file', models.FileField(upload_to='funksional_datas/')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
